CREATE DATABASE IF NOT EXISTS otoku_circle
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE otoku_circle;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  avatar VARCHAR(5) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  area VARCHAR(120) DEFAULT NULL,
  nearest_station VARCHAR(120) DEFAULT NULL,
  visit_note TEXT,
  visited_at_label VARCHAR(50) DEFAULT NULL,
  help_tag VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
