<?php

$imageUrls = [
    "salmon"  => "https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?auto=format&fit=crop&w=900&q=80",
    "produce" => "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
    "bento"   => "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80",
    "milk"    => "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=900&q=80",
    "bread"   => "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",
];

$posts = [
    [
        "id"          => 1,
        "type"        => "image",
        "title"       => "Half-price salmon packs at AEON",
        "description" => "Look for the red 50% sticker near the fresh fish corner. Good for dinner tonight.",
        "store"       => "AEON Takamatsu",
        "distance"    => "0.8 km",
        "time"        => "18 min ago",
        "expires"     => "Ends tonight",
        "saving"      => "Save about ¥480",
        "image"       => $imageUrls["salmon"],
        "author"      => "Minh",
        "avatar"      => "M",
        "badge"       => "Trusted",
        "likes"       => 42,
        "comments"    => 9,
        "viewers"     => 18,
        "tags"        => ["#fish", "#dinner", "#kanji-help"],
        "comments_list" => [
            ["name" => "Ana", "copy" => "I just checked this shelf. Still a few packs left."],
            ["name" => "Sam", "copy" => "The sticker says best before today, so cook it soon."],
        ],
    ],
    [
        "id"          => 2,
        "type"        => "text",
        "title"       => "Tip: yellow stickers usually start after 7 PM",
        "description" => "In my local supermarket, bentos and fried food get cheaper after 7 PM. Check the ready-meal area first.",
        "store"       => "Marunaka",
        "distance"    => "1.1 km",
        "time"        => "34 min ago",
        "expires"     => "Useful daily",
        "saving"      => "Save ¥200-¥600",
        "image"       => "",
        "author"      => "Lina",
        "avatar"      => "L",
        "badge"       => "Guide",
        "likes"       => 58,
        "comments"    => 14,
        "viewers"     => 31,
        "tags"        => ["#beginner", "#bento", "#life-tip"],
        "comments_list" => [
            ["name" => "Ravi", "copy" => "This helped me yesterday. The staff marked things down around 19:20."],
            ["name" => "Maya", "copy" => "Same at my store, but weekends start a bit earlier."],
        ],
    ],
    [
        "id"          => 3,
        "type"        => "image",
        "title"       => "Vegetables bundle for curry week",
        "description" => "Potatoes, carrots, onions. The sign says limited quantity, but there were many left.",
        "store"       => "YouMe Town",
        "distance"    => "1.9 km",
        "time"        => "1 hr ago",
        "expires"     => "2 hours left",
        "saving"      => "Save about ¥320",
        "image"       => $imageUrls["produce"],
        "author"      => "Ravi",
        "avatar"      => "R",
        "badge"       => "Helpful",
        "likes"       => 25,
        "comments"    => 5,
        "viewers"     => 12,
        "tags"        => ["#vegetarian", "#curry", "#cheap"],
        "comments_list" => [
            ["name" => "Minh", "copy" => "Great for meal prep. Thanks!"],
        ],
    ],
    [
        "id"          => 4,
        "type"        => "image",
        "title"       => "Bento corner markdown at 8 PM",
        "description" => "Chicken karaage bento dropped from ¥498 to ¥298. No English label, but photo helps.",
        "store"       => "Fuji Grand",
        "distance"    => "2.4 km",
        "time"        => "2 hr ago",
        "expires"     => "Night deal",
        "saving"      => "Save ¥200",
        "image"       => $imageUrls["bento"],
        "author"      => "Ana",
        "avatar"      => "A",
        "badge"       => "Local MVP",
        "likes"       => 36,
        "comments"    => 7,
        "viewers"     => 21,
        "tags"        => ["#bento", "#night", "#photo-help"],
        "comments_list" => [
            ["name" => "Lina", "copy" => "The kanji says chicken, right? Good to know."],
        ],
    ],
    [
        "id"          => 5,
        "type"        => "image",
        "title"       => "Milk discount: check expiry date",
        "description" => "Cheap milk near the back of the dairy shelf. Good if you use it within two days.",
        "store"       => "MaxValu",
        "distance"    => "3.0 km",
        "time"        => "Yesterday",
        "expires"     => "Today only",
        "saving"      => "Save ¥90",
        "image"       => $imageUrls["milk"],
        "author"      => "Sam",
        "avatar"      => "S",
        "badge"       => "New helper",
        "likes"       => 18,
        "comments"    => 3,
        "viewers"     => 6,
        "tags"        => ["#milk", "#breakfast", "#date-check"],
        "comments_list" => [
            ["name" => "Ravi", "copy" => "Good reminder to check the date."],
        ],
    ],
];

$leaders = [
    ["name" => "Ana",  "value" => "¥8,420 saved",      "badge" => "Local MVP"],
    ["name" => "Minh", "value" => "34 useful posts",    "badge" => "Trusted"],
    ["name" => "Lina", "value" => "91 helpful votes",   "badge" => "Guide"],
];

$stores = [
    [
        "name"       => "AEON Takamatsu",
        "area"       => "Takamatsu",
        "station"    => "Near Takamatsu Station",
        "deals"      => "8 posts today",
        "distance"   => "0.8 km",
        "pin"        => "A",
        "tone"       => "mint",
        "created_by" => "Community",
        "note"       => "Big supermarket with fresh fish corner. Discounts start after 7 PM.",
        "verified"   => "User visited",
    ],
    [
        "name"       => "Marunaka",
        "area"       => "Takamatsu",
        "station"    => "Near Ritsurin Station",
        "deals"      => "5 posts today",
        "distance"   => "1.1 km",
        "pin"        => "M",
        "tone"       => "sky",
        "created_by" => "Community",
        "note"       => "Good bento deals in the evening. Yellow stickers after 7 PM.",
        "verified"   => "User visited",
    ],
    [
        "name"       => "YouMe Town",
        "area"       => "Takamatsu",
        "station"    => "Near Katahara-machi Station",
        "deals"      => "4 posts today",
        "distance"   => "1.9 km",
        "pin"        => "Y",
        "tone"       => "amber",
        "created_by" => "Community",
        "note"       => "Vegetable bundles on weekends. Check the produce section.",
        "verified"   => "User visited",
    ],
    [
        "name"       => "Fuji Grand",
        "area"       => "Takamatsu",
        "station"    => "Near Kasuga Station",
        "deals"      => "3 posts today",
        "distance"   => "2.4 km",
        "pin"        => "F",
        "tone"       => "",
        "created_by" => "Community",
        "note"       => "Bento markdown after 8 PM. Photo-friendly labels.",
        "verified"   => "User visited",
    ],
];

$notifications = [
    [
        "icon"   => "heart",
        "title"  => "Ana liked your post",
        "copy"   => "Half-price salmon helped her find dinner tonight.",
        "time"   => "Now",
        "unread" => true,
    ],
    [
        "icon"   => "message-circle",
        "title"  => "New comment from Ravi",
        "copy"   => "He added the exact time Marunaka starts markdowns.",
        "time"   => "12m",
        "unread" => true,
    ],
    [
        "icon"   => "badge-check",
        "title"  => "You earned Trusted helper",
        "copy"   => "Your last 5 posts were marked useful by the community.",
        "time"   => "1h",
        "unread" => false,
    ],
    [
        "icon"   => "map-pin",
        "title"  => "New deal near you",
        "copy"   => "AEON Takamatsu has a fresh fish discount post.",
        "time"   => "2h",
        "unread" => false,
    ],
];
